let numero1 = 15;
let numero2 = 34;
let suma = numero1 + numero2;
let resta = numero1 - numero2;
let multiplicacion = numero1 + numero2;
let division = numero1 / numero2;
let modulo = numero1 % numero2;
let esMayor = numero1 > numero2;
let esMenor = numero1 < numero2;
console.log(suma);
console.log(resta);
console.log(multiplicacion);
console.log(division);
console.log(modulo);
console.log(esMayor);
console.log(esMenor);